/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import java.time.LocalDateTime;

import javaone.feedback.db.tables.AccessToken;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccessTokenRecord extends UpdatableRecordImpl<AccessTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>access_token.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>access_token.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>access_token.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>access_token.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>access_token.token</code>.
     */
    public void setToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>access_token.token</code>.
     */
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>access_token.used</code>.
     */
    public void setUsed(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>access_token.used</code>.
     */
    public Boolean getUsed() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>access_token.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>access_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>access_token.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>access_token.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccessTokenRecord
     */
    public AccessTokenRecord() {
        super(AccessToken.ACCESS_TOKEN);
    }

    /**
     * Create a detached, initialised AccessTokenRecord
     */
    public AccessTokenRecord(Long id, String email, String token, Boolean used, LocalDateTime createdAt, LocalDateTime expiresAt) {
        super(AccessToken.ACCESS_TOKEN);

        setId(id);
        setEmail(email);
        setToken(token);
        setUsed(used);
        setCreatedAt(createdAt);
        setExpiresAt(expiresAt);
        resetChangedOnNotNull();
    }
}
