/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import javaone.feedback.db.tables.FeedbackAnswer;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackAnswerRecord extends UpdatableRecordImpl<FeedbackAnswerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>feedback_answer.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>feedback_answer.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>feedback_answer.response_id</code>.
     */
    public void setResponseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>feedback_answer.response_id</code>.
     */
    public Long getResponseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>feedback_answer.question_id</code>.
     */
    public void setQuestionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>feedback_answer.question_id</code>.
     */
    public Long getQuestionId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>feedback_answer.rating_value</code>.
     */
    public void setRatingValue(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>feedback_answer.rating_value</code>.
     */
    public Integer getRatingValue() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>feedback_answer.text_value</code>.
     */
    public void setTextValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>feedback_answer.text_value</code>.
     */
    public String getTextValue() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackAnswerRecord
     */
    public FeedbackAnswerRecord() {
        super(FeedbackAnswer.FEEDBACK_ANSWER);
    }

    /**
     * Create a detached, initialised FeedbackAnswerRecord
     */
    public FeedbackAnswerRecord(Long id, Long responseId, Long questionId, Integer ratingValue, String textValue) {
        super(FeedbackAnswer.FEEDBACK_ANSWER);

        setId(id);
        setResponseId(responseId);
        setQuestionId(questionId);
        setRatingValue(ratingValue);
        setTextValue(textValue);
        resetChangedOnNotNull();
    }
}
