/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import java.time.LocalDateTime;

import javaone.feedback.db.tables.FeedbackResponse;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackResponseRecord extends UpdatableRecordImpl<FeedbackResponseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>feedback_response.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>feedback_response.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>feedback_response.form_id</code>.
     */
    public void setFormId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>feedback_response.form_id</code>.
     */
    public Long getFormId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>feedback_response.submitted_at</code>.
     */
    public void setSubmittedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>feedback_response.submitted_at</code>.
     */
    public LocalDateTime getSubmittedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackResponseRecord
     */
    public FeedbackResponseRecord() {
        super(FeedbackResponse.FEEDBACK_RESPONSE);
    }

    /**
     * Create a detached, initialised FeedbackResponseRecord
     */
    public FeedbackResponseRecord(Long id, Long formId, LocalDateTime submittedAt) {
        super(FeedbackResponse.FEEDBACK_RESPONSE);

        setId(id);
        setFormId(formId);
        setSubmittedAt(submittedAt);
        resetChangedOnNotNull();
    }
}
