/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import javaone.feedback.db.tables.FeedbackQuestion;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackQuestionRecord extends UpdatableRecordImpl<FeedbackQuestionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>feedback_question.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>feedback_question.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>feedback_question.form_id</code>.
     */
    public void setFormId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>feedback_question.form_id</code>.
     */
    public Long getFormId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>feedback_question.question_text</code>.
     */
    public void setQuestionText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>feedback_question.question_text</code>.
     */
    public String getQuestionText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>feedback_question.question_type</code>.
     */
    public void setQuestionType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>feedback_question.question_type</code>.
     */
    public String getQuestionType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>feedback_question.order_index</code>.
     */
    public void setOrderIndex(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>feedback_question.order_index</code>.
     */
    public Integer getOrderIndex() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackQuestionRecord
     */
    public FeedbackQuestionRecord() {
        super(FeedbackQuestion.FEEDBACK_QUESTION);
    }

    /**
     * Create a detached, initialised FeedbackQuestionRecord
     */
    public FeedbackQuestionRecord(Long id, Long formId, String questionText, String questionType, Integer orderIndex) {
        super(FeedbackQuestion.FEEDBACK_QUESTION);

        setId(id);
        setFormId(formId);
        setQuestionText(questionText);
        setQuestionType(questionType);
        setOrderIndex(orderIndex);
        resetChangedOnNotNull();
    }
}
