/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import javaone.feedback.db.tables.FeedbackForm;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackFormRecord extends UpdatableRecordImpl<FeedbackFormRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>feedback_form.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>feedback_form.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>feedback_form.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>feedback_form.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>feedback_form.speaker_name</code>.
     */
    public void setSpeakerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>feedback_form.speaker_name</code>.
     */
    public String getSpeakerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>feedback_form.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>feedback_form.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>feedback_form.public_token</code>.
     */
    public void setPublicToken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>feedback_form.public_token</code>.
     */
    public String getPublicToken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>feedback_form.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>feedback_form.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>feedback_form.owner_email</code>.
     */
    public void setOwnerEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>feedback_form.owner_email</code>.
     */
    public String getOwnerEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>feedback_form.event_date</code>.
     */
    public void setEventDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>feedback_form.event_date</code>.
     */
    public LocalDate getEventDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>feedback_form.location</code>.
     */
    public void setLocation(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>feedback_form.location</code>.
     */
    public String getLocation() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackFormRecord
     */
    public FeedbackFormRecord() {
        super(FeedbackForm.FEEDBACK_FORM);
    }

    /**
     * Create a detached, initialised FeedbackFormRecord
     */
    public FeedbackFormRecord(Long id, String title, String speakerName, String status, String publicToken, LocalDateTime createdAt, String ownerEmail, LocalDate eventDate, String location) {
        super(FeedbackForm.FEEDBACK_FORM);

        setId(id);
        setTitle(title);
        setSpeakerName(speakerName);
        setStatus(status);
        setPublicToken(publicToken);
        setCreatedAt(createdAt);
        setOwnerEmail(ownerEmail);
        setEventDate(eventDate);
        setLocation(location);
        resetChangedOnNotNull();
    }
}
