/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import java.time.LocalDateTime;

import javaone.feedback.db.tables.FormTemplate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormTemplateRecord extends UpdatableRecordImpl<FormTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>form_template.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>form_template.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>form_template.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>form_template.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>form_template.owner_email</code>.
     */
    public void setOwnerEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>form_template.owner_email</code>.
     */
    public String getOwnerEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>form_template.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>form_template.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormTemplateRecord
     */
    public FormTemplateRecord() {
        super(FormTemplate.FORM_TEMPLATE);
    }

    /**
     * Create a detached, initialised FormTemplateRecord
     */
    public FormTemplateRecord(Long id, String name, String ownerEmail, LocalDateTime createdAt) {
        super(FormTemplate.FORM_TEMPLATE);

        setId(id);
        setName(name);
        setOwnerEmail(ownerEmail);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
