/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables.records;


import javaone.feedback.db.tables.FormShare;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormShareRecord extends UpdatableRecordImpl<FormShareRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>form_share.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>form_share.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>form_share.form_id</code>.
     */
    public void setFormId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>form_share.form_id</code>.
     */
    public Long getFormId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>form_share.shared_with_email</code>.
     */
    public void setSharedWithEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>form_share.shared_with_email</code>.
     */
    public String getSharedWithEmail() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormShareRecord
     */
    public FormShareRecord() {
        super(FormShare.FORM_SHARE);
    }

    /**
     * Create a detached, initialised FormShareRecord
     */
    public FormShareRecord(Long id, Long formId, String sharedWithEmail) {
        super(FormShare.FORM_SHARE);

        setId(id);
        setFormId(formId);
        setSharedWithEmail(sharedWithEmail);
        resetChangedOnNotNull();
    }
}
