/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.records.AccessTokenRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccessToken extends TableImpl<AccessTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>access_token</code>
     */
    public static final AccessToken ACCESS_TOKEN = new AccessToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccessTokenRecord> getRecordType() {
        return AccessTokenRecord.class;
    }

    /**
     * The column <code>access_token.id</code>.
     */
    public final TableField<AccessTokenRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>access_token.email</code>.
     */
    public final TableField<AccessTokenRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>access_token.token</code>.
     */
    public final TableField<AccessTokenRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>access_token.used</code>.
     */
    public final TableField<AccessTokenRecord, Boolean> USED = createField(DSL.name("used"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>access_token.created_at</code>.
     */
    public final TableField<AccessTokenRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>access_token.expires_at</code>.
     */
    public final TableField<AccessTokenRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private AccessToken(Name alias, Table<AccessTokenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccessToken(Name alias, Table<AccessTokenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>access_token</code> table reference
     */
    public AccessToken(String alias) {
        this(DSL.name(alias), ACCESS_TOKEN);
    }

    /**
     * Create an aliased <code>access_token</code> table reference
     */
    public AccessToken(Name alias) {
        this(alias, ACCESS_TOKEN);
    }

    /**
     * Create a <code>access_token</code> table reference
     */
    public AccessToken() {
        this(DSL.name("access_token"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<AccessTokenRecord, Long> getIdentity() {
        return (Identity<AccessTokenRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccessTokenRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8C;
    }

    @Override
    public List<UniqueKey<AccessTokenRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_8C6);
    }

    @Override
    public AccessToken as(String alias) {
        return new AccessToken(DSL.name(alias), this);
    }

    @Override
    public AccessToken as(Name alias) {
        return new AccessToken(alias, this);
    }

    @Override
    public AccessToken as(Table<?> alias) {
        return new AccessToken(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccessToken rename(String name) {
        return new AccessToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccessToken rename(Name name) {
        return new AccessToken(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccessToken rename(Table<?> name) {
        return new AccessToken(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccessToken where(Condition condition) {
        return new AccessToken(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccessToken where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccessToken where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccessToken where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccessToken where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccessToken where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccessToken where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccessToken where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccessToken whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccessToken whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
