/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.FeedbackQuestion.FeedbackQuestionPath;
import javaone.feedback.db.tables.FeedbackResponse.FeedbackResponsePath;
import javaone.feedback.db.tables.FormShare.FormSharePath;
import javaone.feedback.db.tables.records.FeedbackFormRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackForm extends TableImpl<FeedbackFormRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>feedback_form</code>
     */
    public static final FeedbackForm FEEDBACK_FORM = new FeedbackForm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedbackFormRecord> getRecordType() {
        return FeedbackFormRecord.class;
    }

    /**
     * The column <code>feedback_form.id</code>.
     */
    public final TableField<FeedbackFormRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>feedback_form.title</code>.
     */
    public final TableField<FeedbackFormRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>feedback_form.speaker_name</code>.
     */
    public final TableField<FeedbackFormRecord, String> SPEAKER_NAME = createField(DSL.name("speaker_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>feedback_form.status</code>.
     */
    public final TableField<FeedbackFormRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>feedback_form.public_token</code>.
     */
    public final TableField<FeedbackFormRecord, String> PUBLIC_TOKEN = createField(DSL.name("public_token"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>feedback_form.created_at</code>.
     */
    public final TableField<FeedbackFormRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>feedback_form.owner_email</code>.
     */
    public final TableField<FeedbackFormRecord, String> OWNER_EMAIL = createField(DSL.name("owner_email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>feedback_form.event_date</code>.
     */
    public final TableField<FeedbackFormRecord, LocalDate> EVENT_DATE = createField(DSL.name("event_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>feedback_form.location</code>.
     */
    public final TableField<FeedbackFormRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(255), this, "");

    private FeedbackForm(Name alias, Table<FeedbackFormRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FeedbackForm(Name alias, Table<FeedbackFormRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>feedback_form</code> table reference
     */
    public FeedbackForm(String alias) {
        this(DSL.name(alias), FEEDBACK_FORM);
    }

    /**
     * Create an aliased <code>feedback_form</code> table reference
     */
    public FeedbackForm(Name alias) {
        this(alias, FEEDBACK_FORM);
    }

    /**
     * Create a <code>feedback_form</code> table reference
     */
    public FeedbackForm() {
        this(DSL.name("feedback_form"), null);
    }

    public <O extends Record> FeedbackForm(Table<O> path, ForeignKey<O, FeedbackFormRecord> childPath, InverseForeignKey<O, FeedbackFormRecord> parentPath) {
        super(path, childPath, parentPath, FEEDBACK_FORM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FeedbackFormPath extends FeedbackForm implements Path<FeedbackFormRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FeedbackFormPath(Table<O> path, ForeignKey<O, FeedbackFormRecord> childPath, InverseForeignKey<O, FeedbackFormRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FeedbackFormPath(Name alias, Table<FeedbackFormRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FeedbackFormPath as(String alias) {
            return new FeedbackFormPath(DSL.name(alias), this);
        }

        @Override
        public FeedbackFormPath as(Name alias) {
            return new FeedbackFormPath(alias, this);
        }

        @Override
        public FeedbackFormPath as(Table<?> alias) {
            return new FeedbackFormPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FeedbackFormRecord, Long> getIdentity() {
        return (Identity<FeedbackFormRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FeedbackFormRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    public List<UniqueKey<FeedbackFormRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_8B);
    }

    private transient FeedbackQuestionPath _constraint_77;

    /**
     * Get the implicit to-many join path to the <code>feedback_question</code>
     * table, via the <code>CONSTRAINT_77</code> key
     */
    public FeedbackQuestionPath constraint_77() {
        if (_constraint_77 == null)
            _constraint_77 = new FeedbackQuestionPath(this, null, Keys.CONSTRAINT_77.getInverseKey());

        return _constraint_77;
    }

    private transient FeedbackResponsePath _constraintA9;

    /**
     * Get the implicit to-many join path to the <code>feedback_response</code>
     * table, via the <code>CONSTRAINT_A9</code> key
     */
    public FeedbackResponsePath constraintA9() {
        if (_constraintA9 == null)
            _constraintA9 = new FeedbackResponsePath(this, null, Keys.CONSTRAINT_A9.getInverseKey());

        return _constraintA9;
    }

    private transient FormSharePath _formShare;

    /**
     * Get the implicit to-many join path to the <code>form_share</code> table
     */
    public FormSharePath formShare() {
        if (_formShare == null)
            _formShare = new FormSharePath(this, null, Keys.CONSTRAINT_FD.getInverseKey());

        return _formShare;
    }

    private transient FeedbackQuestionPath _feedbackQuestionFormIdFkey;

    /**
     * Get the implicit to-many join path to the <code>feedback_question</code>
     * table, via the <code>feedback_question_form_id_fkey</code> key
     */
    public FeedbackQuestionPath feedbackQuestionFormIdFkey() {
        if (_feedbackQuestionFormIdFkey == null)
            _feedbackQuestionFormIdFkey = new FeedbackQuestionPath(this, null, Keys.FEEDBACK_QUESTION_FORM_ID_FKEY.getInverseKey());

        return _feedbackQuestionFormIdFkey;
    }

    private transient FeedbackResponsePath _feedbackResponseFormIdFkey;

    /**
     * Get the implicit to-many join path to the <code>feedback_response</code>
     * table, via the <code>feedback_response_form_id_fkey</code> key
     */
    public FeedbackResponsePath feedbackResponseFormIdFkey() {
        if (_feedbackResponseFormIdFkey == null)
            _feedbackResponseFormIdFkey = new FeedbackResponsePath(this, null, Keys.FEEDBACK_RESPONSE_FORM_ID_FKEY.getInverseKey());

        return _feedbackResponseFormIdFkey;
    }

    @Override
    public FeedbackForm as(String alias) {
        return new FeedbackForm(DSL.name(alias), this);
    }

    @Override
    public FeedbackForm as(Name alias) {
        return new FeedbackForm(alias, this);
    }

    @Override
    public FeedbackForm as(Table<?> alias) {
        return new FeedbackForm(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackForm rename(String name) {
        return new FeedbackForm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackForm rename(Name name) {
        return new FeedbackForm(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackForm rename(Table<?> name) {
        return new FeedbackForm(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackForm where(Condition condition) {
        return new FeedbackForm(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackForm where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackForm where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackForm where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackForm where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackForm where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackForm where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackForm where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackForm whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackForm whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
