/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.FeedbackQuestion.FeedbackQuestionPath;
import javaone.feedback.db.tables.FeedbackResponse.FeedbackResponsePath;
import javaone.feedback.db.tables.records.FeedbackAnswerRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackAnswer extends TableImpl<FeedbackAnswerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>feedback_answer</code>
     */
    public static final FeedbackAnswer FEEDBACK_ANSWER = new FeedbackAnswer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedbackAnswerRecord> getRecordType() {
        return FeedbackAnswerRecord.class;
    }

    /**
     * The column <code>feedback_answer.id</code>.
     */
    public final TableField<FeedbackAnswerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>feedback_answer.response_id</code>.
     */
    public final TableField<FeedbackAnswerRecord, Long> RESPONSE_ID = createField(DSL.name("response_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>feedback_answer.question_id</code>.
     */
    public final TableField<FeedbackAnswerRecord, Long> QUESTION_ID = createField(DSL.name("question_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>feedback_answer.rating_value</code>.
     */
    public final TableField<FeedbackAnswerRecord, Integer> RATING_VALUE = createField(DSL.name("rating_value"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>feedback_answer.text_value</code>.
     */
    public final TableField<FeedbackAnswerRecord, String> TEXT_VALUE = createField(DSL.name("text_value"), SQLDataType.VARCHAR(2000), this, "");

    private FeedbackAnswer(Name alias, Table<FeedbackAnswerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FeedbackAnswer(Name alias, Table<FeedbackAnswerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>feedback_answer</code> table reference
     */
    public FeedbackAnswer(String alias) {
        this(DSL.name(alias), FEEDBACK_ANSWER);
    }

    /**
     * Create an aliased <code>feedback_answer</code> table reference
     */
    public FeedbackAnswer(Name alias) {
        this(alias, FEEDBACK_ANSWER);
    }

    /**
     * Create a <code>feedback_answer</code> table reference
     */
    public FeedbackAnswer() {
        this(DSL.name("feedback_answer"), null);
    }

    public <O extends Record> FeedbackAnswer(Table<O> path, ForeignKey<O, FeedbackAnswerRecord> childPath, InverseForeignKey<O, FeedbackAnswerRecord> parentPath) {
        super(path, childPath, parentPath, FEEDBACK_ANSWER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FeedbackAnswerPath extends FeedbackAnswer implements Path<FeedbackAnswerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FeedbackAnswerPath(Table<O> path, ForeignKey<O, FeedbackAnswerRecord> childPath, InverseForeignKey<O, FeedbackAnswerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FeedbackAnswerPath(Name alias, Table<FeedbackAnswerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FeedbackAnswerPath as(String alias) {
            return new FeedbackAnswerPath(DSL.name(alias), this);
        }

        @Override
        public FeedbackAnswerPath as(Name alias) {
            return new FeedbackAnswerPath(alias, this);
        }

        @Override
        public FeedbackAnswerPath as(Table<?> alias) {
            return new FeedbackAnswerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FeedbackAnswerRecord, Long> getIdentity() {
        return (Identity<FeedbackAnswerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FeedbackAnswerRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A3;
    }

    @Override
    public List<ForeignKey<FeedbackAnswerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_A33, Keys.CONSTRAINT_A332, Keys.FEEDBACK_ANSWER_QUESTION_ID_FKEY, Keys.FEEDBACK_ANSWER_RESPONSE_ID_FKEY);
    }

    private transient FeedbackResponsePath _constraintA33;

    /**
     * Get the implicit join path to the <code>feedback_response</code> table,
     * via the <code>CONSTRAINT_A33</code> key.
     */
    public FeedbackResponsePath constraintA33() {
        if (_constraintA33 == null)
            _constraintA33 = new FeedbackResponsePath(this, Keys.CONSTRAINT_A33, null);

        return _constraintA33;
    }

    private transient FeedbackQuestionPath _constraintA332;

    /**
     * Get the implicit join path to the <code>feedback_question</code> table,
     * via the <code>CONSTRAINT_A332</code> key.
     */
    public FeedbackQuestionPath constraintA332() {
        if (_constraintA332 == null)
            _constraintA332 = new FeedbackQuestionPath(this, Keys.CONSTRAINT_A332, null);

        return _constraintA332;
    }

    private transient FeedbackQuestionPath _feedbackAnswerQuestionIdFkey;

    /**
     * Get the implicit join path to the <code>feedback_question</code> table,
     * via the <code>feedback_answer_question_id_fkey</code> key.
     */
    public FeedbackQuestionPath feedbackAnswerQuestionIdFkey() {
        if (_feedbackAnswerQuestionIdFkey == null)
            _feedbackAnswerQuestionIdFkey = new FeedbackQuestionPath(this, Keys.FEEDBACK_ANSWER_QUESTION_ID_FKEY, null);

        return _feedbackAnswerQuestionIdFkey;
    }

    private transient FeedbackResponsePath _feedbackAnswerResponseIdFkey;

    /**
     * Get the implicit join path to the <code>feedback_response</code> table,
     * via the <code>feedback_answer_response_id_fkey</code> key.
     */
    public FeedbackResponsePath feedbackAnswerResponseIdFkey() {
        if (_feedbackAnswerResponseIdFkey == null)
            _feedbackAnswerResponseIdFkey = new FeedbackResponsePath(this, Keys.FEEDBACK_ANSWER_RESPONSE_ID_FKEY, null);

        return _feedbackAnswerResponseIdFkey;
    }

    @Override
    public FeedbackAnswer as(String alias) {
        return new FeedbackAnswer(DSL.name(alias), this);
    }

    @Override
    public FeedbackAnswer as(Name alias) {
        return new FeedbackAnswer(alias, this);
    }

    @Override
    public FeedbackAnswer as(Table<?> alias) {
        return new FeedbackAnswer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackAnswer rename(String name) {
        return new FeedbackAnswer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackAnswer rename(Name name) {
        return new FeedbackAnswer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackAnswer rename(Table<?> name) {
        return new FeedbackAnswer(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackAnswer where(Condition condition) {
        return new FeedbackAnswer(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackAnswer where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackAnswer where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackAnswer where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackAnswer where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackAnswer where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackAnswer where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackAnswer where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackAnswer whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackAnswer whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
