/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.FeedbackAnswer.FeedbackAnswerPath;
import javaone.feedback.db.tables.FeedbackForm.FeedbackFormPath;
import javaone.feedback.db.tables.records.FeedbackResponseRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackResponse extends TableImpl<FeedbackResponseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>feedback_response</code>
     */
    public static final FeedbackResponse FEEDBACK_RESPONSE = new FeedbackResponse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedbackResponseRecord> getRecordType() {
        return FeedbackResponseRecord.class;
    }

    /**
     * The column <code>feedback_response.id</code>.
     */
    public final TableField<FeedbackResponseRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>feedback_response.form_id</code>.
     */
    public final TableField<FeedbackResponseRecord, Long> FORM_ID = createField(DSL.name("form_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>feedback_response.submitted_at</code>.
     */
    public final TableField<FeedbackResponseRecord, LocalDateTime> SUBMITTED_AT = createField(DSL.name("submitted_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private FeedbackResponse(Name alias, Table<FeedbackResponseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FeedbackResponse(Name alias, Table<FeedbackResponseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>feedback_response</code> table reference
     */
    public FeedbackResponse(String alias) {
        this(DSL.name(alias), FEEDBACK_RESPONSE);
    }

    /**
     * Create an aliased <code>feedback_response</code> table reference
     */
    public FeedbackResponse(Name alias) {
        this(alias, FEEDBACK_RESPONSE);
    }

    /**
     * Create a <code>feedback_response</code> table reference
     */
    public FeedbackResponse() {
        this(DSL.name("feedback_response"), null);
    }

    public <O extends Record> FeedbackResponse(Table<O> path, ForeignKey<O, FeedbackResponseRecord> childPath, InverseForeignKey<O, FeedbackResponseRecord> parentPath) {
        super(path, childPath, parentPath, FEEDBACK_RESPONSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FeedbackResponsePath extends FeedbackResponse implements Path<FeedbackResponseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FeedbackResponsePath(Table<O> path, ForeignKey<O, FeedbackResponseRecord> childPath, InverseForeignKey<O, FeedbackResponseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FeedbackResponsePath(Name alias, Table<FeedbackResponseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FeedbackResponsePath as(String alias) {
            return new FeedbackResponsePath(DSL.name(alias), this);
        }

        @Override
        public FeedbackResponsePath as(Name alias) {
            return new FeedbackResponsePath(alias, this);
        }

        @Override
        public FeedbackResponsePath as(Table<?> alias) {
            return new FeedbackResponsePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FeedbackResponseRecord, Long> getIdentity() {
        return (Identity<FeedbackResponseRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FeedbackResponseRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    @Override
    public List<ForeignKey<FeedbackResponseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_A9, Keys.FEEDBACK_RESPONSE_FORM_ID_FKEY);
    }

    private transient FeedbackFormPath _constraintA9;

    /**
     * Get the implicit join path to the <code>feedback_form</code> table, via
     * the <code>CONSTRAINT_A9</code> key.
     */
    public FeedbackFormPath constraintA9() {
        if (_constraintA9 == null)
            _constraintA9 = new FeedbackFormPath(this, Keys.CONSTRAINT_A9, null);

        return _constraintA9;
    }

    private transient FeedbackFormPath _feedbackResponseFormIdFkey;

    /**
     * Get the implicit join path to the <code>feedback_form</code> table, via
     * the <code>feedback_response_form_id_fkey</code> key.
     */
    public FeedbackFormPath feedbackResponseFormIdFkey() {
        if (_feedbackResponseFormIdFkey == null)
            _feedbackResponseFormIdFkey = new FeedbackFormPath(this, Keys.FEEDBACK_RESPONSE_FORM_ID_FKEY, null);

        return _feedbackResponseFormIdFkey;
    }

    private transient FeedbackAnswerPath _constraintA33;

    /**
     * Get the implicit to-many join path to the <code>feedback_answer</code>
     * table, via the <code>CONSTRAINT_A33</code> key
     */
    public FeedbackAnswerPath constraintA33() {
        if (_constraintA33 == null)
            _constraintA33 = new FeedbackAnswerPath(this, null, Keys.CONSTRAINT_A33.getInverseKey());

        return _constraintA33;
    }

    private transient FeedbackAnswerPath _feedbackAnswerResponseIdFkey;

    /**
     * Get the implicit to-many join path to the <code>feedback_answer</code>
     * table, via the <code>feedback_answer_response_id_fkey</code> key
     */
    public FeedbackAnswerPath feedbackAnswerResponseIdFkey() {
        if (_feedbackAnswerResponseIdFkey == null)
            _feedbackAnswerResponseIdFkey = new FeedbackAnswerPath(this, null, Keys.FEEDBACK_ANSWER_RESPONSE_ID_FKEY.getInverseKey());

        return _feedbackAnswerResponseIdFkey;
    }

    @Override
    public FeedbackResponse as(String alias) {
        return new FeedbackResponse(DSL.name(alias), this);
    }

    @Override
    public FeedbackResponse as(Name alias) {
        return new FeedbackResponse(alias, this);
    }

    @Override
    public FeedbackResponse as(Table<?> alias) {
        return new FeedbackResponse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackResponse rename(String name) {
        return new FeedbackResponse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackResponse rename(Name name) {
        return new FeedbackResponse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackResponse rename(Table<?> name) {
        return new FeedbackResponse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackResponse where(Condition condition) {
        return new FeedbackResponse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackResponse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackResponse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackResponse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackResponse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackResponse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackResponse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackResponse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackResponse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackResponse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
