/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.FeedbackAnswer.FeedbackAnswerPath;
import javaone.feedback.db.tables.FeedbackForm.FeedbackFormPath;
import javaone.feedback.db.tables.records.FeedbackQuestionRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedbackQuestion extends TableImpl<FeedbackQuestionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>feedback_question</code>
     */
    public static final FeedbackQuestion FEEDBACK_QUESTION = new FeedbackQuestion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedbackQuestionRecord> getRecordType() {
        return FeedbackQuestionRecord.class;
    }

    /**
     * The column <code>feedback_question.id</code>.
     */
    public final TableField<FeedbackQuestionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>feedback_question.form_id</code>.
     */
    public final TableField<FeedbackQuestionRecord, Long> FORM_ID = createField(DSL.name("form_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>feedback_question.question_text</code>.
     */
    public final TableField<FeedbackQuestionRecord, String> QUESTION_TEXT = createField(DSL.name("question_text"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>feedback_question.question_type</code>.
     */
    public final TableField<FeedbackQuestionRecord, String> QUESTION_TYPE = createField(DSL.name("question_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>feedback_question.order_index</code>.
     */
    public final TableField<FeedbackQuestionRecord, Integer> ORDER_INDEX = createField(DSL.name("order_index"), SQLDataType.INTEGER.nullable(false), this, "");

    private FeedbackQuestion(Name alias, Table<FeedbackQuestionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FeedbackQuestion(Name alias, Table<FeedbackQuestionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>feedback_question</code> table reference
     */
    public FeedbackQuestion(String alias) {
        this(DSL.name(alias), FEEDBACK_QUESTION);
    }

    /**
     * Create an aliased <code>feedback_question</code> table reference
     */
    public FeedbackQuestion(Name alias) {
        this(alias, FEEDBACK_QUESTION);
    }

    /**
     * Create a <code>feedback_question</code> table reference
     */
    public FeedbackQuestion() {
        this(DSL.name("feedback_question"), null);
    }

    public <O extends Record> FeedbackQuestion(Table<O> path, ForeignKey<O, FeedbackQuestionRecord> childPath, InverseForeignKey<O, FeedbackQuestionRecord> parentPath) {
        super(path, childPath, parentPath, FEEDBACK_QUESTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FeedbackQuestionPath extends FeedbackQuestion implements Path<FeedbackQuestionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FeedbackQuestionPath(Table<O> path, ForeignKey<O, FeedbackQuestionRecord> childPath, InverseForeignKey<O, FeedbackQuestionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FeedbackQuestionPath(Name alias, Table<FeedbackQuestionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FeedbackQuestionPath as(String alias) {
            return new FeedbackQuestionPath(DSL.name(alias), this);
        }

        @Override
        public FeedbackQuestionPath as(Name alias) {
            return new FeedbackQuestionPath(alias, this);
        }

        @Override
        public FeedbackQuestionPath as(Table<?> alias) {
            return new FeedbackQuestionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FeedbackQuestionRecord, Long> getIdentity() {
        return (Identity<FeedbackQuestionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FeedbackQuestionRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    @Override
    public List<ForeignKey<FeedbackQuestionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_77, Keys.FEEDBACK_QUESTION_FORM_ID_FKEY);
    }

    private transient FeedbackFormPath _constraint_77;

    /**
     * Get the implicit join path to the <code>feedback_form</code> table, via
     * the <code>CONSTRAINT_77</code> key.
     */
    public FeedbackFormPath constraint_77() {
        if (_constraint_77 == null)
            _constraint_77 = new FeedbackFormPath(this, Keys.CONSTRAINT_77, null);

        return _constraint_77;
    }

    private transient FeedbackFormPath _feedbackQuestionFormIdFkey;

    /**
     * Get the implicit join path to the <code>feedback_form</code> table, via
     * the <code>feedback_question_form_id_fkey</code> key.
     */
    public FeedbackFormPath feedbackQuestionFormIdFkey() {
        if (_feedbackQuestionFormIdFkey == null)
            _feedbackQuestionFormIdFkey = new FeedbackFormPath(this, Keys.FEEDBACK_QUESTION_FORM_ID_FKEY, null);

        return _feedbackQuestionFormIdFkey;
    }

    private transient FeedbackAnswerPath _constraintA332;

    /**
     * Get the implicit to-many join path to the <code>feedback_answer</code>
     * table, via the <code>CONSTRAINT_A332</code> key
     */
    public FeedbackAnswerPath constraintA332() {
        if (_constraintA332 == null)
            _constraintA332 = new FeedbackAnswerPath(this, null, Keys.CONSTRAINT_A332.getInverseKey());

        return _constraintA332;
    }

    private transient FeedbackAnswerPath _feedbackAnswerQuestionIdFkey;

    /**
     * Get the implicit to-many join path to the <code>feedback_answer</code>
     * table, via the <code>feedback_answer_question_id_fkey</code> key
     */
    public FeedbackAnswerPath feedbackAnswerQuestionIdFkey() {
        if (_feedbackAnswerQuestionIdFkey == null)
            _feedbackAnswerQuestionIdFkey = new FeedbackAnswerPath(this, null, Keys.FEEDBACK_ANSWER_QUESTION_ID_FKEY.getInverseKey());

        return _feedbackAnswerQuestionIdFkey;
    }

    @Override
    public FeedbackQuestion as(String alias) {
        return new FeedbackQuestion(DSL.name(alias), this);
    }

    @Override
    public FeedbackQuestion as(Name alias) {
        return new FeedbackQuestion(alias, this);
    }

    @Override
    public FeedbackQuestion as(Table<?> alias) {
        return new FeedbackQuestion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackQuestion rename(String name) {
        return new FeedbackQuestion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackQuestion rename(Name name) {
        return new FeedbackQuestion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedbackQuestion rename(Table<?> name) {
        return new FeedbackQuestion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackQuestion where(Condition condition) {
        return new FeedbackQuestion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackQuestion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackQuestion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackQuestion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackQuestion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackQuestion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackQuestion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedbackQuestion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackQuestion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedbackQuestion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
