/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.FeedbackForm.FeedbackFormPath;
import javaone.feedback.db.tables.records.FormShareRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormShare extends TableImpl<FormShareRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>form_share</code>
     */
    public static final FormShare FORM_SHARE = new FormShare();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FormShareRecord> getRecordType() {
        return FormShareRecord.class;
    }

    /**
     * The column <code>form_share.id</code>.
     */
    public final TableField<FormShareRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>form_share.form_id</code>.
     */
    public final TableField<FormShareRecord, Long> FORM_ID = createField(DSL.name("form_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>form_share.shared_with_email</code>.
     */
    public final TableField<FormShareRecord, String> SHARED_WITH_EMAIL = createField(DSL.name("shared_with_email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private FormShare(Name alias, Table<FormShareRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FormShare(Name alias, Table<FormShareRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>form_share</code> table reference
     */
    public FormShare(String alias) {
        this(DSL.name(alias), FORM_SHARE);
    }

    /**
     * Create an aliased <code>form_share</code> table reference
     */
    public FormShare(Name alias) {
        this(alias, FORM_SHARE);
    }

    /**
     * Create a <code>form_share</code> table reference
     */
    public FormShare() {
        this(DSL.name("form_share"), null);
    }

    public <O extends Record> FormShare(Table<O> path, ForeignKey<O, FormShareRecord> childPath, InverseForeignKey<O, FormShareRecord> parentPath) {
        super(path, childPath, parentPath, FORM_SHARE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FormSharePath extends FormShare implements Path<FormShareRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FormSharePath(Table<O> path, ForeignKey<O, FormShareRecord> childPath, InverseForeignKey<O, FormShareRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FormSharePath(Name alias, Table<FormShareRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FormSharePath as(String alias) {
            return new FormSharePath(DSL.name(alias), this);
        }

        @Override
        public FormSharePath as(Name alias) {
            return new FormSharePath(alias, this);
        }

        @Override
        public FormSharePath as(Table<?> alias) {
            return new FormSharePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FormShareRecord, Long> getIdentity() {
        return (Identity<FormShareRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FormShareRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    public List<UniqueKey<FormShareRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_FDE);
    }

    @Override
    public List<ForeignKey<FormShareRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_FD);
    }

    private transient FeedbackFormPath _feedbackForm;

    /**
     * Get the implicit join path to the <code>feedback_form</code> table.
     */
    public FeedbackFormPath feedbackForm() {
        if (_feedbackForm == null)
            _feedbackForm = new FeedbackFormPath(this, Keys.CONSTRAINT_FD, null);

        return _feedbackForm;
    }

    @Override
    public FormShare as(String alias) {
        return new FormShare(DSL.name(alias), this);
    }

    @Override
    public FormShare as(Name alias) {
        return new FormShare(alias, this);
    }

    @Override
    public FormShare as(Table<?> alias) {
        return new FormShare(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FormShare rename(String name) {
        return new FormShare(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FormShare rename(Name name) {
        return new FormShare(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FormShare rename(Table<?> name) {
        return new FormShare(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormShare where(Condition condition) {
        return new FormShare(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormShare where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormShare where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormShare where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormShare where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormShare where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormShare where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormShare where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormShare whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormShare whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
