/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.time.LocalDateTime;
import java.util.Collection;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.TemplateQuestion.TemplateQuestionPath;
import javaone.feedback.db.tables.records.FormTemplateRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormTemplate extends TableImpl<FormTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>form_template</code>
     */
    public static final FormTemplate FORM_TEMPLATE = new FormTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FormTemplateRecord> getRecordType() {
        return FormTemplateRecord.class;
    }

    /**
     * The column <code>form_template.id</code>.
     */
    public final TableField<FormTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("NEXT VALUE FOR \"PUBLIC\".\"form_template_seq\""), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>form_template.name</code>.
     */
    public final TableField<FormTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>form_template.owner_email</code>.
     */
    public final TableField<FormTemplateRecord, String> OWNER_EMAIL = createField(DSL.name("owner_email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>form_template.created_at</code>.
     */
    public final TableField<FormTemplateRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private FormTemplate(Name alias, Table<FormTemplateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FormTemplate(Name alias, Table<FormTemplateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>form_template</code> table reference
     */
    public FormTemplate(String alias) {
        this(DSL.name(alias), FORM_TEMPLATE);
    }

    /**
     * Create an aliased <code>form_template</code> table reference
     */
    public FormTemplate(Name alias) {
        this(alias, FORM_TEMPLATE);
    }

    /**
     * Create a <code>form_template</code> table reference
     */
    public FormTemplate() {
        this(DSL.name("form_template"), null);
    }

    public <O extends Record> FormTemplate(Table<O> path, ForeignKey<O, FormTemplateRecord> childPath, InverseForeignKey<O, FormTemplateRecord> parentPath) {
        super(path, childPath, parentPath, FORM_TEMPLATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FormTemplatePath extends FormTemplate implements Path<FormTemplateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FormTemplatePath(Table<O> path, ForeignKey<O, FormTemplateRecord> childPath, InverseForeignKey<O, FormTemplateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FormTemplatePath(Name alias, Table<FormTemplateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FormTemplatePath as(String alias) {
            return new FormTemplatePath(DSL.name(alias), this);
        }

        @Override
        public FormTemplatePath as(Name alias) {
            return new FormTemplatePath(alias, this);
        }

        @Override
        public FormTemplatePath as(Table<?> alias) {
            return new FormTemplatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<FormTemplateRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6;
    }

    private transient TemplateQuestionPath _templateQuestion;

    /**
     * Get the implicit to-many join path to the <code>template_question</code>
     * table
     */
    public TemplateQuestionPath templateQuestion() {
        if (_templateQuestion == null)
            _templateQuestion = new TemplateQuestionPath(this, null, Keys.CONSTRAINT_C1.getInverseKey());

        return _templateQuestion;
    }

    @Override
    public FormTemplate as(String alias) {
        return new FormTemplate(DSL.name(alias), this);
    }

    @Override
    public FormTemplate as(Name alias) {
        return new FormTemplate(alias, this);
    }

    @Override
    public FormTemplate as(Table<?> alias) {
        return new FormTemplate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FormTemplate rename(String name) {
        return new FormTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FormTemplate rename(Name name) {
        return new FormTemplate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FormTemplate rename(Table<?> name) {
        return new FormTemplate(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormTemplate where(Condition condition) {
        return new FormTemplate(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormTemplate where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormTemplate where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormTemplate where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormTemplate where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormTemplate where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormTemplate where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FormTemplate where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormTemplate whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FormTemplate whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
