/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javaone.feedback.db.DefaultSchema;
import javaone.feedback.db.Keys;
import javaone.feedback.db.tables.FormTemplate.FormTemplatePath;
import javaone.feedback.db.tables.records.TemplateQuestionRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TemplateQuestion extends TableImpl<TemplateQuestionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>template_question</code>
     */
    public static final TemplateQuestion TEMPLATE_QUESTION = new TemplateQuestion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TemplateQuestionRecord> getRecordType() {
        return TemplateQuestionRecord.class;
    }

    /**
     * The column <code>template_question.id</code>.
     */
    public final TableField<TemplateQuestionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("NEXT VALUE FOR \"PUBLIC\".\"template_question_seq\""), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>template_question.template_id</code>.
     */
    public final TableField<TemplateQuestionRecord, Long> TEMPLATE_ID = createField(DSL.name("template_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>template_question.question_text</code>.
     */
    public final TableField<TemplateQuestionRecord, String> QUESTION_TEXT = createField(DSL.name("question_text"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>template_question.question_type</code>.
     */
    public final TableField<TemplateQuestionRecord, String> QUESTION_TYPE = createField(DSL.name("question_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>template_question.order_index</code>.
     */
    public final TableField<TemplateQuestionRecord, Integer> ORDER_INDEX = createField(DSL.name("order_index"), SQLDataType.INTEGER.nullable(false), this, "");

    private TemplateQuestion(Name alias, Table<TemplateQuestionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TemplateQuestion(Name alias, Table<TemplateQuestionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>template_question</code> table reference
     */
    public TemplateQuestion(String alias) {
        this(DSL.name(alias), TEMPLATE_QUESTION);
    }

    /**
     * Create an aliased <code>template_question</code> table reference
     */
    public TemplateQuestion(Name alias) {
        this(alias, TEMPLATE_QUESTION);
    }

    /**
     * Create a <code>template_question</code> table reference
     */
    public TemplateQuestion() {
        this(DSL.name("template_question"), null);
    }

    public <O extends Record> TemplateQuestion(Table<O> path, ForeignKey<O, TemplateQuestionRecord> childPath, InverseForeignKey<O, TemplateQuestionRecord> parentPath) {
        super(path, childPath, parentPath, TEMPLATE_QUESTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TemplateQuestionPath extends TemplateQuestion implements Path<TemplateQuestionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TemplateQuestionPath(Table<O> path, ForeignKey<O, TemplateQuestionRecord> childPath, InverseForeignKey<O, TemplateQuestionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TemplateQuestionPath(Name alias, Table<TemplateQuestionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TemplateQuestionPath as(String alias) {
            return new TemplateQuestionPath(DSL.name(alias), this);
        }

        @Override
        public TemplateQuestionPath as(Name alias) {
            return new TemplateQuestionPath(alias, this);
        }

        @Override
        public TemplateQuestionPath as(Table<?> alias) {
            return new TemplateQuestionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TemplateQuestionRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    public List<ForeignKey<TemplateQuestionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_C1);
    }

    private transient FormTemplatePath _formTemplate;

    /**
     * Get the implicit join path to the <code>form_template</code> table.
     */
    public FormTemplatePath formTemplate() {
        if (_formTemplate == null)
            _formTemplate = new FormTemplatePath(this, Keys.CONSTRAINT_C1, null);

        return _formTemplate;
    }

    @Override
    public TemplateQuestion as(String alias) {
        return new TemplateQuestion(DSL.name(alias), this);
    }

    @Override
    public TemplateQuestion as(Name alias) {
        return new TemplateQuestion(alias, this);
    }

    @Override
    public TemplateQuestion as(Table<?> alias) {
        return new TemplateQuestion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateQuestion rename(String name) {
        return new TemplateQuestion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateQuestion rename(Name name) {
        return new TemplateQuestion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TemplateQuestion rename(Table<?> name) {
        return new TemplateQuestion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateQuestion where(Condition condition) {
        return new TemplateQuestion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateQuestion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateQuestion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateQuestion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateQuestion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateQuestion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateQuestion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TemplateQuestion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateQuestion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TemplateQuestion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
