/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db;


import java.util.Arrays;
import java.util.List;

import javaone.feedback.db.tables.AccessToken;
import javaone.feedback.db.tables.FeedbackAnswer;
import javaone.feedback.db.tables.FeedbackForm;
import javaone.feedback.db.tables.FeedbackQuestion;
import javaone.feedback.db.tables.FeedbackResponse;
import javaone.feedback.db.tables.FormShare;
import javaone.feedback.db.tables.FormTemplate;
import javaone.feedback.db.tables.TemplateQuestion;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>access_token</code>.
     */
    public final AccessToken ACCESS_TOKEN = AccessToken.ACCESS_TOKEN;

    /**
     * The table <code>feedback_answer</code>.
     */
    public final FeedbackAnswer FEEDBACK_ANSWER = FeedbackAnswer.FEEDBACK_ANSWER;

    /**
     * The table <code>feedback_form</code>.
     */
    public final FeedbackForm FEEDBACK_FORM = FeedbackForm.FEEDBACK_FORM;

    /**
     * The table <code>feedback_question</code>.
     */
    public final FeedbackQuestion FEEDBACK_QUESTION = FeedbackQuestion.FEEDBACK_QUESTION;

    /**
     * The table <code>feedback_response</code>.
     */
    public final FeedbackResponse FEEDBACK_RESPONSE = FeedbackResponse.FEEDBACK_RESPONSE;

    /**
     * The table <code>form_share</code>.
     */
    public final FormShare FORM_SHARE = FormShare.FORM_SHARE;

    /**
     * The table <code>form_template</code>.
     */
    public final FormTemplate FORM_TEMPLATE = FormTemplate.FORM_TEMPLATE;

    /**
     * The table <code>template_question</code>.
     */
    public final TemplateQuestion TEMPLATE_QUESTION = TemplateQuestion.TEMPLATE_QUESTION;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.FORM_TEMPLATE_SEQ,
            Sequences.TEMPLATE_QUESTION_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccessToken.ACCESS_TOKEN,
            FeedbackAnswer.FEEDBACK_ANSWER,
            FeedbackForm.FEEDBACK_FORM,
            FeedbackQuestion.FEEDBACK_QUESTION,
            FeedbackResponse.FEEDBACK_RESPONSE,
            FormShare.FORM_SHARE,
            FormTemplate.FORM_TEMPLATE,
            TemplateQuestion.TEMPLATE_QUESTION
        );
    }
}
