/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db;


import javaone.feedback.db.tables.AccessToken;
import javaone.feedback.db.tables.FeedbackAnswer;
import javaone.feedback.db.tables.FeedbackForm;
import javaone.feedback.db.tables.FeedbackQuestion;
import javaone.feedback.db.tables.FeedbackResponse;
import javaone.feedback.db.tables.FormShare;
import javaone.feedback.db.tables.FormTemplate;
import javaone.feedback.db.tables.TemplateQuestion;
import javaone.feedback.db.tables.records.AccessTokenRecord;
import javaone.feedback.db.tables.records.FeedbackAnswerRecord;
import javaone.feedback.db.tables.records.FeedbackFormRecord;
import javaone.feedback.db.tables.records.FeedbackQuestionRecord;
import javaone.feedback.db.tables.records.FeedbackResponseRecord;
import javaone.feedback.db.tables.records.FormShareRecord;
import javaone.feedback.db.tables.records.FormTemplateRecord;
import javaone.feedback.db.tables.records.TemplateQuestionRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccessTokenRecord> CONSTRAINT_8C = Internal.createUniqueKey(AccessToken.ACCESS_TOKEN, DSL.name("CONSTRAINT_8C"), new TableField[] { AccessToken.ACCESS_TOKEN.ID }, true);
    public static final UniqueKey<AccessTokenRecord> CONSTRAINT_8C6 = Internal.createUniqueKey(AccessToken.ACCESS_TOKEN, DSL.name("CONSTRAINT_8C6"), new TableField[] { AccessToken.ACCESS_TOKEN.TOKEN }, true);
    public static final UniqueKey<FeedbackAnswerRecord> CONSTRAINT_A3 = Internal.createUniqueKey(FeedbackAnswer.FEEDBACK_ANSWER, DSL.name("CONSTRAINT_A3"), new TableField[] { FeedbackAnswer.FEEDBACK_ANSWER.ID }, true);
    public static final UniqueKey<FeedbackFormRecord> CONSTRAINT_8 = Internal.createUniqueKey(FeedbackForm.FEEDBACK_FORM, DSL.name("CONSTRAINT_8"), new TableField[] { FeedbackForm.FEEDBACK_FORM.ID }, true);
    public static final UniqueKey<FeedbackFormRecord> CONSTRAINT_8B = Internal.createUniqueKey(FeedbackForm.FEEDBACK_FORM, DSL.name("CONSTRAINT_8B"), new TableField[] { FeedbackForm.FEEDBACK_FORM.PUBLIC_TOKEN }, true);
    public static final UniqueKey<FeedbackQuestionRecord> CONSTRAINT_7 = Internal.createUniqueKey(FeedbackQuestion.FEEDBACK_QUESTION, DSL.name("CONSTRAINT_7"), new TableField[] { FeedbackQuestion.FEEDBACK_QUESTION.ID }, true);
    public static final UniqueKey<FeedbackResponseRecord> CONSTRAINT_A = Internal.createUniqueKey(FeedbackResponse.FEEDBACK_RESPONSE, DSL.name("CONSTRAINT_A"), new TableField[] { FeedbackResponse.FEEDBACK_RESPONSE.ID }, true);
    public static final UniqueKey<FormShareRecord> CONSTRAINT_F = Internal.createUniqueKey(FormShare.FORM_SHARE, DSL.name("CONSTRAINT_F"), new TableField[] { FormShare.FORM_SHARE.ID }, true);
    public static final UniqueKey<FormShareRecord> CONSTRAINT_FDE = Internal.createUniqueKey(FormShare.FORM_SHARE, DSL.name("CONSTRAINT_FDE"), new TableField[] { FormShare.FORM_SHARE.FORM_ID, FormShare.FORM_SHARE.SHARED_WITH_EMAIL }, true);
    public static final UniqueKey<FormTemplateRecord> CONSTRAINT_6 = Internal.createUniqueKey(FormTemplate.FORM_TEMPLATE, DSL.name("CONSTRAINT_6"), new TableField[] { FormTemplate.FORM_TEMPLATE.ID }, true);
    public static final UniqueKey<TemplateQuestionRecord> CONSTRAINT_C = Internal.createUniqueKey(TemplateQuestion.TEMPLATE_QUESTION, DSL.name("CONSTRAINT_C"), new TableField[] { TemplateQuestion.TEMPLATE_QUESTION.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FeedbackAnswerRecord, FeedbackResponseRecord> CONSTRAINT_A33 = Internal.createForeignKey(FeedbackAnswer.FEEDBACK_ANSWER, DSL.name("CONSTRAINT_A33"), new TableField[] { FeedbackAnswer.FEEDBACK_ANSWER.RESPONSE_ID }, Keys.CONSTRAINT_A, new TableField[] { FeedbackResponse.FEEDBACK_RESPONSE.ID }, true);
    public static final ForeignKey<FeedbackAnswerRecord, FeedbackQuestionRecord> CONSTRAINT_A332 = Internal.createForeignKey(FeedbackAnswer.FEEDBACK_ANSWER, DSL.name("CONSTRAINT_A332"), new TableField[] { FeedbackAnswer.FEEDBACK_ANSWER.QUESTION_ID }, Keys.CONSTRAINT_7, new TableField[] { FeedbackQuestion.FEEDBACK_QUESTION.ID }, true);
    public static final ForeignKey<FeedbackAnswerRecord, FeedbackQuestionRecord> FEEDBACK_ANSWER_QUESTION_ID_FKEY = Internal.createForeignKey(FeedbackAnswer.FEEDBACK_ANSWER, DSL.name("feedback_answer_question_id_fkey"), new TableField[] { FeedbackAnswer.FEEDBACK_ANSWER.QUESTION_ID }, Keys.CONSTRAINT_7, new TableField[] { FeedbackQuestion.FEEDBACK_QUESTION.ID }, true);
    public static final ForeignKey<FeedbackAnswerRecord, FeedbackResponseRecord> FEEDBACK_ANSWER_RESPONSE_ID_FKEY = Internal.createForeignKey(FeedbackAnswer.FEEDBACK_ANSWER, DSL.name("feedback_answer_response_id_fkey"), new TableField[] { FeedbackAnswer.FEEDBACK_ANSWER.RESPONSE_ID }, Keys.CONSTRAINT_A, new TableField[] { FeedbackResponse.FEEDBACK_RESPONSE.ID }, true);
    public static final ForeignKey<FeedbackQuestionRecord, FeedbackFormRecord> CONSTRAINT_77 = Internal.createForeignKey(FeedbackQuestion.FEEDBACK_QUESTION, DSL.name("CONSTRAINT_77"), new TableField[] { FeedbackQuestion.FEEDBACK_QUESTION.FORM_ID }, Keys.CONSTRAINT_8, new TableField[] { FeedbackForm.FEEDBACK_FORM.ID }, true);
    public static final ForeignKey<FeedbackQuestionRecord, FeedbackFormRecord> FEEDBACK_QUESTION_FORM_ID_FKEY = Internal.createForeignKey(FeedbackQuestion.FEEDBACK_QUESTION, DSL.name("feedback_question_form_id_fkey"), new TableField[] { FeedbackQuestion.FEEDBACK_QUESTION.FORM_ID }, Keys.CONSTRAINT_8, new TableField[] { FeedbackForm.FEEDBACK_FORM.ID }, true);
    public static final ForeignKey<FeedbackResponseRecord, FeedbackFormRecord> CONSTRAINT_A9 = Internal.createForeignKey(FeedbackResponse.FEEDBACK_RESPONSE, DSL.name("CONSTRAINT_A9"), new TableField[] { FeedbackResponse.FEEDBACK_RESPONSE.FORM_ID }, Keys.CONSTRAINT_8, new TableField[] { FeedbackForm.FEEDBACK_FORM.ID }, true);
    public static final ForeignKey<FeedbackResponseRecord, FeedbackFormRecord> FEEDBACK_RESPONSE_FORM_ID_FKEY = Internal.createForeignKey(FeedbackResponse.FEEDBACK_RESPONSE, DSL.name("feedback_response_form_id_fkey"), new TableField[] { FeedbackResponse.FEEDBACK_RESPONSE.FORM_ID }, Keys.CONSTRAINT_8, new TableField[] { FeedbackForm.FEEDBACK_FORM.ID }, true);
    public static final ForeignKey<FormShareRecord, FeedbackFormRecord> CONSTRAINT_FD = Internal.createForeignKey(FormShare.FORM_SHARE, DSL.name("CONSTRAINT_FD"), new TableField[] { FormShare.FORM_SHARE.FORM_ID }, Keys.CONSTRAINT_8, new TableField[] { FeedbackForm.FEEDBACK_FORM.ID }, true);
    public static final ForeignKey<TemplateQuestionRecord, FormTemplateRecord> CONSTRAINT_C1 = Internal.createForeignKey(TemplateQuestion.TEMPLATE_QUESTION, DSL.name("CONSTRAINT_C1"), new TableField[] { TemplateQuestion.TEMPLATE_QUESTION.TEMPLATE_ID }, Keys.CONSTRAINT_6, new TableField[] { FormTemplate.FORM_TEMPLATE.ID }, true);
}
