/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>form_template_seq</code>
     */
    public static final Sequence<Long> FORM_TEMPLATE_SEQ = Internal.createSequence("form_template_seq", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>template_question_seq</code>
     */
    public static final Sequence<Long> TEMPLATE_QUESTION_SEQ = Internal.createSequence("template_question_seq", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);
}
