/*
 * This file is generated by jOOQ.
 */
package javaone.feedback.db;


import javaone.feedback.db.tables.AccessToken;
import javaone.feedback.db.tables.FeedbackAnswer;
import javaone.feedback.db.tables.FeedbackForm;
import javaone.feedback.db.tables.FeedbackQuestion;
import javaone.feedback.db.tables.FeedbackResponse;
import javaone.feedback.db.tables.FormShare;
import javaone.feedback.db.tables.FormTemplate;
import javaone.feedback.db.tables.TemplateQuestion;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>access_token</code>.
     */
    public static final AccessToken ACCESS_TOKEN = AccessToken.ACCESS_TOKEN;

    /**
     * The table <code>feedback_answer</code>.
     */
    public static final FeedbackAnswer FEEDBACK_ANSWER = FeedbackAnswer.FEEDBACK_ANSWER;

    /**
     * The table <code>feedback_form</code>.
     */
    public static final FeedbackForm FEEDBACK_FORM = FeedbackForm.FEEDBACK_FORM;

    /**
     * The table <code>feedback_question</code>.
     */
    public static final FeedbackQuestion FEEDBACK_QUESTION = FeedbackQuestion.FEEDBACK_QUESTION;

    /**
     * The table <code>feedback_response</code>.
     */
    public static final FeedbackResponse FEEDBACK_RESPONSE = FeedbackResponse.FEEDBACK_RESPONSE;

    /**
     * The table <code>form_share</code>.
     */
    public static final FormShare FORM_SHARE = FormShare.FORM_SHARE;

    /**
     * The table <code>form_template</code>.
     */
    public static final FormTemplate FORM_TEMPLATE = FormTemplate.FORM_TEMPLATE;

    /**
     * The table <code>template_question</code>.
     */
    public static final TemplateQuestion TEMPLATE_QUESTION = TemplateQuestion.TEMPLATE_QUESTION;
}
